---
- name: Include firewall rules for DHCP
  ansible.builtin.include_tasks:
    file: ../firewall/main.yml

- name: Install packages
  ansible.builtin.command:
    cmd: yum install dhcp* -y

- name: Configure DHCP server
  ansible.builtin.template:
    src: "{{ vars_dhcp_template_path }}"
    dest: "{{ vars_dhcp_file }}"
    mode: "{{ vars_mode }}"
  notify: Restart DHCP service