---
- name: Include SSH rules for the gateway VM
  ansible.builtin.include_tasks:
    file: ../ssh_setup.yml

- name: Include firewall rules for the gateway VM
  ansible.builtin.include_tasks:
    file: ../firewall/main.yml
