---
# tasks file for ansible
- name: Creating a VM
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../var/main.yml
    - ../var/secrets.yml
  tasks:
# Define a list of VMs to create
    - name: Create VMs
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        name: "{{ item.name }}"
        template: "{{ template_path }}"
        datacenter: "{{ datacenter_name }}"
        folder: "{{ folder_path }}"
        hardware:
          memory_mb: "{{ vm_ram_mb }}"
          num_cpus: "{{ vm_cpu_n }}"
        networks: "{{ item.networks }}"
        wait_for_ip_address: true
        state: poweredon
      delegate_to: localhost
      loop:
        - name: "{{ vm_name_gateway }}"
          networks:
            - name: "{{ gateway_network }}"
              ip: "{{ gateway_ip }}"
              netmask: "{{ network_mask }}"
              gateway: "{{ external_gateway_ip }}"
              type: "static"
              start_connected: true
            - name: "{{ internal_network }}"
              ip: "{{ internal_gateway_ip }}"
              netmask: "{{ network_mask }}"
              type: "static"
              start_connected: true

        - name: "{{ vm_name_dns }}"
          networks:
            - name: "{{ internal_network }}"
              ip: "{{ dns_ip }}"
              netmask: "{{ network_mask }}"
              gateway: "{{ internal_gateway_ip }}"
              type: "static"
              start_connected: true

        - name: "{{ vm_name_dhcp }}"
          networks:
            - name: "{{ internal_network }}"
              ip: "{{ dhcp_ip }}"
              netmask: "{{ network_mask }}"
              gateway: "{{ internal_gateway_ip }}"
              type: "static"
              start_connected: true

        - name: "{{ vm_name_webserver }}"
          networks:
            - name: "{{ internal_network }}"
              start_connected: true