---
# vars file for ansible
# Variables for all VMs
vars_vcenter_password: "Renegade187!"
vars_vcenter_validate_certs: false
vars_datacenter_name: "Development"
vars_template_path: "/Development/vm/Laura/CentOS8_Blank"
vars_folder_path: "/Laura/Ansible"
vars_network_mask: "255.255.255.0"
vars_internal_network: "Laura"
vars_vm_ram_mb: 2048
vars_vm_cpu_n: 2
vars_ansible_user: "root"
vars_mode: "0644"

# Gateway VM variables
vars_vm_name_gateway: "gateway_ansible"
vars_gateway_network: "VM Network"
vars_gateway_ip: "172.16.6.200"
vars_external_gateway_ip: "172.16.0.1"
vars_internal_gateway_ip: "10.0.0.1"

# DHCP VM variables
vars_vm_name_dhcp: "dhcp_ansible"
vars_dhcp_ip: "10.0.0.2"
vars_dhcp_template_path: "{{ playbook_dir | realpath }}/../templates/dhcp_conf.j2"
vars_dhcp_file: "/etc/dhcp/dhcpd.conf"

# DNS VM variables
vars_vm_name_dns: "dns_ansible"
vars_dns_ip: "10.0.0.3"
vars_dns_serial: 2024091602
vars_named_template_path: "{{ playbook_dir | realpath }}/roles/templates/dns_named.j2"
vars_zone_template_path: "{{ playbook_dir | realpath }}/roles/templates/dns_zone.j2"
vars_hosts_file: "/etc/hosts"
vars_domain: "lmw.local"
vars_named_conf: "/etc/named.conf"
vars_fwd_zone_file: "/var/named/fwd.lmw.local"
vars_rev_zone_file: "/var/named/rev.lmw.local"
vars_bind_listen_ipv4_port: 53
vars_bind_listen_ipv4:
  - "127.0.0.1"
  - "10.0.0.3"
vars_bind_listen_ipv6_port: 53
vars_bind_listen_ipv6: []
vars_bind_dir: "/var/named"
vars_bind_allow_query:
  - "localhost"
  - "10.0.0.0/24"
  - "any"
vars_bind_forwarders:
  - "8.8.8.8"
  - "8.8.4.4"
vars_bind_forward_only: true
vars_bind_recursion: true
vars_bind_allow_recursion:
  - "localhost"
vars_bind_acls: []
vars_bind_check_names: "warn"
vars_zones:
  - name: "{{ vars_domain }}"
    type: "master"
    file: "{{ vars_fwd_zone_file }}"
    allow_update: "none"
  - name: "0.0.10.in-addr.arpa"
    type: "master"
    file: "{{ vars_rev_zone_file }}"
    allow_update: "none"

# Variables specific to webserver
vars_vm_name_webserver: "webserver_ansible"
vars_webserver_port: 3000
vars_webserver_target_url: "https://jsonplaceholder.typicode.com/todos"