---
# Main playbook to create and configure VMs using Ansible and vSphere.
# Step 1: Creates the 4 essential VMs - Gateway, DNS, DHCP and Webserver
- name: Create VMs
  hosts: localhost
  gather_facts: false
  vars_files:
    - roles/vars/main.yml
    - roles/vars/secrets.yml
  tasks:
    - name: Create the essential VMs (Gateway, DNS, DHCP, Webserver)
      ansible.builtin.include_tasks: roles/tasks/main.yml

# Step 2: Configure the Gateway VM, adding port IP forwarding and firewall rules.
- name: Configure Gateway VM
  hosts: gateway_ansible
  gather_facts: true
  become: true
  vars_files:
    - roles/vars/main.yml
  tasks:
    - name: Include tasks for the Gateway VM
      ansible.builtin.include_tasks: roles/tasks/gateway.yml

# Step 3: Configure the DNS VM, sets up forward and reverse zones and activates DNS service.
- name: Configure DNS VM
  hosts: dns_ansible
  gather_facts: true
  become: true
  vars_files:
    - roles/vars/main.yml
  tasks:
    - name: Include tasks for the DNS VM
      ansible.builtin.include_tasks: roles/tasks/dns.yml
  handlers:
    - name: Restart and enable named service
      ansible.builtin.service:
        name: named
        state: restarted
        enabled: true

# Step 4: Configure the DHCP VM, handles IP ranges and reservations and starts the DHCP service.
- name: Configure DHCP VM
  hosts: dhcp_ansible
  gather_facts: true
  become: true
  vars_files:
    - roles/vars/main.yml
  tasks:
    - name: Include tasks for the DHCP VM
      ansible.builtin.include_tasks: roles/tasks/dhcp.yml
  handlers:
    - name: Restart DHCP service
      ansible.builtin.service:
        name: dhcpd
        state: restarted
        enabled: true

# Step 5: Configure the Webserver VM, loads a git repository and displays JSON.
- name: Configure webserver VM
  hosts: webservers
  gather_facts: true
  become: true
  vars_files:
    - roles/vars/main.yml
    - roles/vars/secrets.yml
  tasks:
    - name: Ensure known_hosts file exists
      ansible.builtin.file:
        path: /root/.ssh/known_hosts
        state: touch  # This will create the file if it doesn't exist
        mode: "{{ vars_mode }}"
    - name: Ensure all webserver IPs are in known_hosts
      ansible.builtin.shell: "ssh-keyscan -H {{ inventory_hostname }} >> /root/.ssh/known_hosts"
      args:
        creates: /root/.ssh/known_hosts
      when: ansible_hostname is defined

    - name: Include tasks for the webserver VM
      ansible.builtin.include_tasks: roles/tasks/webserver.yml