---
# handlers file for ansible
- name: Restart and enable named service
  ansible.builtin.service:
    name: named
    state: restarted
    enabled: true

- name: Restart DHCP service
  ansible.builtin.service:
    name: dhcpd
    state: restarted
    enabled: true